// 1. click button to generate a password

var generateBtn = document.querySelector("#generate");

 

// function to generate password

function generatePassword() {

 

    //select criteria for password 

   // created varaible which holds random characters/numbers generated by For Loop

  var getRandomUpper = [];

  for (var i = 0; i < 26; i++) {

    var x = String.fromCharCode(Math.floor(Math.random() * 26) + 65);

    getRandomUpper.push(x);

    

  }

  var getRandomLower = [];

  for (var i = 0; i < 26; i++) {

    var x = String.fromCharCode(Math.floor(Math.random() * 26) + 97);

    getRandomLower.push(x);

  

  }

 

  var getRandomNumber = [];

  for (var i = 0; i < 10; i++) {

    var x = String.fromCharCode(Math.floor(Math.random() * 10) + 48);

    getRandomNumber.push(x);

    

  }

  var specialChar = ["~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "-", "=", "{", "}", "|", "[", "]", ";", "<", ">", "?", "/",];

 

  var getRandomSpecialChar = [];

  for (var i = 0; i < 25; i++) {

    var x = specialChar[Math.floor(Math.random() * specialChar.length)];

    getRandomSpecialChar.push(x);

  }

 

  //this variable will have all selected charater type + length stored

  var validUserInput = [];

 

  // this variable will have userInput prompt captrued 

  var userInput = prompt("Choose your password length");

  var isCancellation = [null, undefined].filter(function(x){ return userInput == x }).length > 0;

 

  if(isCancellation) {

    return;

  }

  var isPromptingAgain = userInput.length == 0;

 

  if(isPromptingAgain) {

    alert("Please enter valid length range between 8 and 128");

    generatePassword();

    return;

  }

 

  if (Number.isNaN(parsed) || userInput < 8 || userInput > 128) {

    alert("Please enter valid length range between 8 and 128");

    return myPassword = "";

  }

 

  var parsed = parseInt(userInput);




var upper = confirm("Does your password includes upppercase letters ?");

var lower = confirm("Does your password includes lowecase letters ?");

var numbers = confirm ("Does your password includes numbers letters ?");

var special = confirm("Does your password includes special characters ?");

 

var typecount = lower + upper + numbers + special;

 

var arr =[{upper}, {lower}, {numbers}, {special}].filter(item => Object.values(item)[0]);

console.log(typecount);

console.log(arr);






  

  

  // variable that holds the generated password

  var myPassword = "";

 

  // for loop that chooses random characters in the arrays user chose

  for (var i = 0; i < userInput; i++) {

    var index = Math.floor(Math.random() * validUserInput.length);

    myPassword += validUserInput[index] + "";

  }

  //B. generate password (using selected criteria!)

  // Returns user generated password

  return myPassword;

}

 

  // Write password to the #password input

function writePassword() {

  var password = generatePassword();

  var passwordText = document.querySelector("#password");

 

  passwordText.value = password;

}

////-alert or write it to the page

// Add event listener to generate button

generateBtn.addEventListener("click", writePassword);

